spring:
    profiles:
        active: native
    cloud:
        config:
            server:
                native:
                    searchLocations: classpath:config/
    config:
        name: configserver

server:
  port: 8888

endpoints:
    restart:
      enabled: true